### ISSUE TITLE
php warning in admin

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/rbp-documentation-cpt#4]
Just saw that Query Monitor was red in the toolbar when viewing the downloads list in the admin. Clicked it and it shows a PHP warning for this plugin.

**Comment by d4mation** [comment]
Looks to be related to #3 and realbig/rbm-cpts#4

I'll take care of realbig/rbm-cpts#4 which should solve this.

**Comment by d4mation** [comment]
Uploaded changes to the Server and nothing shows up in Query Monitor for it anymore 👍
