### ISSUE TITLE
Maintain adding anchor link to URL when clicking on child section

### ISSUE THREAD

**Issue by joelworsham** [realbigplugins/rbp-documentation-cpt#6]
It does not add the anchor link to the URL. It would be handy so people can share specific sections. Like I was about to copy/paste it into the plugin but it didn't append the hash, so I have to do it manually

**Comment by d4mation** [comment]
Just pushed this change to Live.

It will change the Anchor in the URL automatically as you scroll as well, so if a section is very small (Because it hasn't had any content added to it) it may skip over it to the next one.
