### ISSUE TITLE
Back button in browser broken

### ISSUE THREAD

**Issue by joelworsham** [realbigplugins/rbp-documentation-cpt#8]
I came into https://realbigplugins.com/docs/learndash-gradebook/#report-card from a link within the gradebook plugin. I then hit back and it didn't work, hit a few more times but it just jumps around the page, changing the hash, infinitely. I'm assuming you're pushing a history state? I think it might be a little intrusive currently because I can't get off the page :P

**Comment by d4mation** [comment]
Ugh, yeah. I'm not pushing a History State personally but Foundation is :/

It is so dumb. http://foundation.zurb.com/sites/docs/magellan.html#js-options

The Deep Linking option alters the URL __and__ the history. It should be two separate options in my opinion.

I might be able to listen for sections in the Nav becoming "Active" and altering the URL myself. That's probably the only way around it.

**Comment by d4mation** [comment]
That was actually easier than I thought it would be.

```
( function( $ ) {

    $( '.magellan' ).on( 'update.zf.magellan', function( event, activeElement ) {

        // Updates the Hash in the URL without altering the History
        history.replaceState( undefined, undefined, activeElement[0].hash );

    } );

} )( jQuery );
```

[Browser Compatibility is _okay_](https://developer.mozilla.org/en-US/docs/Web/API/History_API#Browser_compatibility). In this case I guess they just don't get the functionality if their browser doesn't support it. I am going to provide another option in realbigplugins/theme2016#36 anyway.

Changes will be pushed here in just a moment~
