### ISSUE TITLE
Add EDD Email Tag for Documentation List

### ISSUE THREAD

**Issue by d4mation** [realbigplugins/rbp-documentation-cpt#9]
Just rigged this up. 

![image](https://cloud.githubusercontent.com/assets/7770631/24429858/de8a1184-13e1-11e7-8771-50231b7b34d3.png)

Here's a preview from MailCatcher:

![image](https://cloud.githubusercontent.com/assets/7770631/24429807/ad8b9cce-13e1-11e7-970b-b0edf766aea3.png)

Nothing special. Tried to make it very clear.

What do you think, @BigActual? I'll make whatever changes and then push it live.

**Comment by BigActual** [comment]
I'd simply add "Need help getting started. Let us help:"

**Comment by d4mation** [comment]
All set :+1:
